==62927== Memcheck, a memory error detector
==62927== Copyright (C) 2002-2024, and GNU GPL'd, by Julian Seward et al.
==62927== Using Valgrind-3.23.0 and LibVEX; rerun with -h for copyright info
==62927== Command: ./push_swap 8 9 2 3 0 1 5 4 6 7
==62927== Parent PID: 62908
==62927== 
==62927== Invalid free() / delete / delete[] / realloc()
==62927==    at 0x48478EF: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==62927==    by 0x1094AB: free_stack (utils.c:42)
==62927==    by 0x1094FE: clear_and_exit (error.c:29)
==62927==    by 0x1090B6: main (main.c:34)
==62927==  Address 0x10d060 is 0 bytes inside data symbol "body.0"
==62927== 
==62927== Invalid read of size 8
==62927==    at 0x1094A3: free_stack (utils.c:41)
==62927==    by 0x1094FE: clear_and_exit (error.c:29)
==62927==    by 0x1090B6: main (main.c:34)
==62927==  Address 0x1a is not stack'd, malloc'd or (recently) free'd
==62927== 
==62927== 
==62927== Process terminating with default action of signal 11 (SIGSEGV)
==62927==  Access not within mapped region at address 0x1A
==62927==    at 0x1094A3: free_stack (utils.c:41)
==62927==    by 0x1094FE: clear_and_exit (error.c:29)
==62927==    by 0x1090B6: main (main.c:34)
==62927==  If you believe this happened as a result of a stack
==62927==  overflow in your program's main thread (unlikely but
==62927==  possible), you can try to increase the size of the
==62927==  main thread stack using the --main-stacksize= flag.
==62927==  The main thread stack size used in this run was 8388608.
==62927== 
==62927== FILE DESCRIPTORS: 6 open (3 std) at exit.
==62927== Open file descriptor 20: /home/lhenriqu/.vscode-server/data/logs/20250123T141858/remoteagent.log
==62927==    <inherited from parent>
==62927== 
==62927== Open file descriptor 19: /home/lhenriqu/.vscode-server/data/logs/20250123T141858/ptyhost.log
==62927==    <inherited from parent>
==62927== 
==62927== Open file descriptor 3: /home/lhenriqu/42Sp/GitHub/push_swap/valgrind.log
==62927==    <inherited from parent>
==62927== 
==62927== 
==62927== HEAP SUMMARY:
==62927==     in use at exit: 240 bytes in 10 blocks
==62927==   total heap usage: 10 allocs, 1 frees, 240 bytes allocated
==62927== 
==62927== 24 bytes in 1 blocks are still reachable in loss record 1 of 3
==62927==    at 0x48447A8: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==62927==    by 0x109C42: ft_calloc (in /home/lhenriqu/42Sp/GitHub/push_swap/push_swap)
==62927==    by 0x1093A8: create_node (stack.c:28)
==62927==    by 0x1093A8: link_node (stack.c:40)
==62927==    by 0x109302: ft_init_numbers (init.c:40)
==62927==    by 0x109098: main (main.c:24)
==62927== 
==62927== 192 bytes in 8 blocks are indirectly lost in loss record 2 of 3
==62927==    at 0x48447A8: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==62927==    by 0x109C42: ft_calloc (in /home/lhenriqu/42Sp/GitHub/push_swap/push_swap)
==62927==    by 0x1093A8: create_node (stack.c:28)
==62927==    by 0x1093A8: link_node (stack.c:40)
==62927==    by 0x109302: ft_init_numbers (init.c:40)
==62927==    by 0x109098: main (main.c:24)
==62927== 
==62927== 216 (24 direct, 192 indirect) bytes in 1 blocks are definitely lost in loss record 3 of 3
==62927==    at 0x48447A8: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==62927==    by 0x109C42: ft_calloc (in /home/lhenriqu/42Sp/GitHub/push_swap/push_swap)
==62927==    by 0x1093A8: create_node (stack.c:28)
==62927==    by 0x1093A8: link_node (stack.c:40)
==62927==    by 0x109302: ft_init_numbers (init.c:40)
==62927==    by 0x109098: main (main.c:24)
==62927== 
==62927== LEAK SUMMARY:
==62927==    definitely lost: 24 bytes in 1 blocks
==62927==    indirectly lost: 192 bytes in 8 blocks
==62927==      possibly lost: 0 bytes in 0 blocks
==62927==    still reachable: 24 bytes in 1 blocks
==62927==         suppressed: 0 bytes in 0 blocks
==62927== 
==62927== ERROR SUMMARY: 6 errors from 6 contexts (suppressed: 0 from 0)
==62927== 
==62927== 1 errors in context 1 of 6:
==62927== Invalid read of size 8
==62927==    at 0x1094A3: free_stack (utils.c:41)
==62927==    by 0x1094FE: clear_and_exit (error.c:29)
==62927==    by 0x1090B6: main (main.c:34)
==62927==  Address 0x1a is not stack'd, malloc'd or (recently) free'd
==62927== 
==62927== 
==62927== 1 errors in context 2 of 6:
==62927== Invalid free() / delete / delete[] / realloc()
==62927==    at 0x48478EF: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==62927==    by 0x1094AB: free_stack (utils.c:42)
==62927==    by 0x1094FE: clear_and_exit (error.c:29)
==62927==    by 0x1090B6: main (main.c:34)
==62927==  Address 0x10d060 is 0 bytes inside data symbol "body.0"
==62927== 
==62927== ERROR SUMMARY: 6 errors from 6 contexts (suppressed: 0 from 0)
